<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="JModelFactory"
    nsURI="http://jmodel" nsPrefix="jmodel">
  <eClassifiers xsi:type="ecore:EClass" name="JModel">
    <eStructuralFeatures xsi:type="ecore:EReference" name="packages" lowerBound="1"
        upperBound="-1" eType="#//JPackage"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="JPackage">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="packageName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nsPrefix" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nsUri" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="JClass"/>
  <eClassifiers xsi:type="ecore:EClass" name="JInterface"/>
  <eClassifiers xsi:type="ecore:EClass" name="JProperty"/>
  <eClassifiers xsi:type="ecore:EClass" name="IReporting" abstract="true" interface="true">
    <eOperations name="toString" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eOperations name="toReport" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractJClass">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
